import type { Metadata } from "next";
import "./globals.css";
import SmoothScrolling from "@/animation/SmoothScrolling";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
        <Footer />
      </body>
    </html>
  );
}
