const titleMap: { [key: string]: string } = {
    'cairo-tours': 'Cairo Tours: Ancient Pyramids and Vibrant City Life',
    'cairo-day-tours': 'Cairo Day Tours: Explore the Heart of Egypt',
    'giza-day-tours': 'Giza Day Tours: Visit the Great Pyramids and Sphinx',
    'giza-tours': 'Giza Tours: Discover the Wonders of the Ancient World',
    'alexandria-tours': 'Alexandria Tours: From Ancient Ruins to the Sea',
    'alexandria-day-tours': 'Alexandria Day Tours: A Quick Historical Retreat',
    'luxor-tours': 'Luxor Tours: Walk Through the Valley of Kings',
    'luxor-day-tours': 'Luxor Day Tours: A Journey to Ancient Thebes',
    'aswan-tours': 'Aswan Tours: Nubian Culture and River Views',
    'aswan-day-tours': 'Aswan Day Tours: The Essence of the Nile',
    'hurghada-tours': 'Hurghada Tours: Red Sea Adventures Await',
    'hurghada-day-tours': 'Hurghada Day Tours: Sun, Sand, and Sea',
    'sharm-el-sheikh-tours': 'Sharm El Sheikh Tours: Luxurious Escape by the Red Sea',
    'sharm-el-sheikh-day-tours': 'Sharm El Sheikh Day Tours: Adventure and Relaxation Combined',
    'siwa-tours': 'Siwa Tours: An Oasis of Culture and History',
    'siwa-day-tours': 'Siwa Day Tours: Discovering the Desert’s Charm',
    'dahab-tours': 'Dahab Tours: Dive and Explore the Bedouin Lifestyle',
    'dahab-day-tours': 'Dahab Day Tours: Adventures in the Red Sea and Beyond',
    'cultural-tours': 'Cultural Tours: Dive Deep into Local Traditions and Heritage',
    'adventure-tours': 'Adventure Tours: Thrilling Expeditions for the Fearless',
    'beach-tours': 'Beach Tours: Serene Beachfront Escapes in Pristine Locations',
    'private-tours': 'Private Tours: Exclusive and Personalized Travel Experiences',
    'group-tours': 'Group Tours: Shared Adventures in Iconic Destinations',
    '1-day-tours': '1-Day Tours: Quick Escapes with Rich Experiences',
    'budget-tours': 'Budget Tours: Affordable Trips Without Compromising Quality',
    'food-tours': 'Food Tours: Culinary Journeys Through Local Flavors',
    'meditation-tours': 'Meditation Tours: Peaceful Retreats for Mind and Soul',
    'historical-tours': 'Historical Tours: Exploring the Richness of the Past',
    'spiritual-tours': 'Spiritual Tours: Journeys of Inner Peace and Discovery',
    'custom-tours': 'Custom Tours: Tailored Itineraries for Your Perfect Trip',
    'city-tours': 'City Tours: Explore the Vibrant Heart of Global Cities',
    'cruise-tours': 'Cruise Tours: Luxurious Explorations by Sea',
    'luxury-tours': 'Luxury Tours: Opulent and Meticulously Crafted Travel Experiences',
    'honeymoon-tours': 'Honeymoon Tours: Romantic Getaways to Celebrate Love',
    'family-tours': 'Family Tours: Enjoyable and Safe Adventures for All Ages',
    '4-days-3-nights-tours': '4 Days 3 Nights Tours: Extended Stays Full of Discovery',
    'nile-cruise-tours': 'Nile Cruise Tours: A Classic Voyage Along Historic Waters',
    '1-day-tour': '1-Day Tour: A Perfect Day of Exploration and Fun',
    'desert-tours': 'Desert Tours: Adventures in the Vast and Mystical Expanse',
    'top-rated-tours': 'Top Rated Tours: Highly Recommended Experiences by Travelers',
    '2-days-tours': '2-Days Tours: Short Breaks Packed with Highlights',
    'shopping-tours': 'Shopping Tours: The Best Retail Experiences in Top Markets',
    'photography-tours': 'Photography Tours: Capture Stunning Scenes from Around the World',
    '12-days-11-nights-tours': '12 Days 11 Nights Tours: Comprehensive Journeys Full of Wonder',
    'family-fours': 'Family Fours Tours: Fun and Educational Trips for Families',
    'religious-tours': 'Religious Tours: Sacred Sites and Spiritual Experiences',
    'luxor-day-tour': 'Luxor Day Tour: A Full Day of Ancient Egyptian Splendor'
};

export default titleMap;