import { GroupSize } from "@/types/createTour";

export const presetOptionNames = [
    { name: "Ticket for great pyramids" },
    { name: "Ticket for sphinx" },
    { name: "Ticket for egyptian museum" },
    { name: "Ticket for khan el khalili" },
    { name: "Ticket for citadel" },
    { name: "Ticket for mohamed ali mosque" },
    { name: "Ticket for coptic cairo" },
    { name: "Ticket for islamic cairo" },
    { name: "Ticket for al azhar park" },
    { name: "Ticket for al azhar mosque" },
    { name: "Ticket for cairo tower" },
    { name: "Ticket for nile cruise" },
    { name: "Ticket for felucca ride" },
    { name: "Ticket for sound and light show" },
    { name: "Ticket for sandboarding" },
    { name: "Desert safari" },
    { name: "Bedouin dinner" },
    { name: "Belly dance show" },
    { name: "Ticket for tanoura show" },
    { name: "Feluka ride" },
    { name: "Quad bike" },
    { name: "Hot air balloon" },
    { name: "Snorkeling" },
    { name: "Diving" },
    { name: "Parasailing" },
    { name: "Banana boat" },
    { name: "Glass boat" },
    { name: "Submarine" },
    { name: "Horse carriage" },
    { name: "Horse ride" },
    { name: "Buggy ride" },
    { name: "Sandboarding" },
    { name: "Desert safari" },
    { name: "Bedouin dinner" },
    { name: "Belly dance show" },
    { name: "Tanoura show" },
    { name: "Alabaster factory" },
    { name: "Papyrus institute" },
    { name: "Perfume factory" },
    { name: "Cotton shop" },
    { name: "Gold shop" },
    { name: "Silver shop" },
    { name: "Spice shop" },
    { name: "Camel ride" },
    { name: "Sound and light show" },
    { name: "Mohamed ali mosque" },
    { name: "Coptic cairo" },
    { name: "Islamic cairo" },
    { name: "Al azhar park" },
    { name: "Al azhar mosque" },
    { name: "Cairo tower" },
    { name: "Nile cruise" },
    { name: "Felucca ride" },
    { name: "Great pyramids" },
    { name: "Sphinx" },
    { name: "Egyptian museum" },
    { name: "Khan el khalili" },
    { name: "Citadel" },
    { name: "Luxor temple" },
    { name: "Inside King Tutankhmen Tomb" },
    { name: "Karnak temple" },
    { name: "Baloon" },
    { name: "Valley of the kings" },
    { name: "Hatshepsut temple" },
    { name: "Colossi of memnon" },
    { name: "Edfu temple" },
    { name: "Kom ombo temple" },
    { name: "Philae temple" },
    { name: "High dam" },
    { name: "Unfinished obelisk" },
    { name: "Private Beach" },
    { name: "German Guide" },
    { name: "Spanish Guide" },
    { name: "Italian Guide" },
    { name: "French Guide" },
    { name: "Russian Guide" },
    { name: "Chinese Guide" },
    { name: "Japanese Guide" },
    { name: "Korean Guide" },
    { name: "Arabic Guide" },
    { name: "Dutch Guide" },
    { name: "Portuguese Guide" },
    { name: "Turkish Guide" },
    { name: "Greek Guide" },
    { name: "Lunch" },
    { name: "Dinner" },
    { name: "Breakfast" },
    { name: "Snacks" },
    { name: "Soft Drinks" },
    { name: "Alcoholic Drinks" },
    { name: "Water" },
    { name: "Accommodation" },
    { name: "Local Transportation" },
    { name: "Entrance Fees" },
    { name: "Guided Tour" },
    { name: "Welcome Drink" },
    { name: "Airport Transfers" },
    { name: "Tipping" },
    { name: "Travel Insurance" },
    { name: "Welcome Drink" },
    { name: "Pickup & Dropoff from Cairo Airport or Hotel" },


];

export const presetInclusions = [
    "An English-Speaking Egyptologist",
    "All Our Transfers Are Arranged By Private A/C Vehicle.",
    "Tasty Lunch In A Local Restaurant.",
    "Complimentary breakfast.",
    "Airport transfers.",
    "Welcome drink.",
    "Guided tour.",
    "Entrance fees.",
    "Local transportation.",
    "Accommodation.",
    "All service charges & taxes.",
    "A Bottle Of Water",
    "Hotel pickup and drop-off",
    "Qualified Egyptologist guide",
    "Private tour",
];

export const presetExclusions = [
    "Entry Fees not included.",
    "Dinner not included.",
    "Personal expenses not covered.",
    "Tipping not included.",
    "Travel insurance not included.",
    "Tickets not included.",
    "Beverages not included.",
    "Alcoholic drinks not included.",
    "Accommodation not included.",
    "Local transportation not included.",
    "Guided tour not included.",
    "Welcome drink not included.",
    "Airport Pickup and drop off (will be for an additional charge)",


];

export const presetWeekDays = [
    { label: "Sunday", value: "Sunday" },
    { label: "Monday", value: "Monday" },
    { label: "Tuesday", value: "Tuesday" },
    { label: "Wednesday", value: "Wednesday" },
    { label: "Thursday", value: "Thursday" },
    { label: "Friday", value: "Friday" },
    { label: "Saturday", value: "Saturday" },
]

export const adultGroupSizes: GroupSize[] = [
    { label: "1 adult", value: 1 },
    { label: "2 adults", value: 2 },
    { label: "3 adults", value: 3 },
    { label: "4 adults", value: 4 },
    { label: "5 adults", value: 5 },
    { label: "6 adults", value: 6 },
    { label: "7 adults", value: 7 },
    { label: "8 adults", value: 8 },
    { label: "9 adults", value: 9 },
    { label: "10 adults", value: 10 }
];

export const childrenGroupSizes: GroupSize[] = [
    { label: "1 child", value: 1 },
    { label: "2 children", value: 2 },
    { label: "3 children", value: 3 },
    { label: "4 children", value: 4 },
    { label: "5 children", value: 5 },
    { label: "6 children", value: 6 },
    { label: "7 children", value: 7 },
    { label: "8 children", value: 8 },
    { label: "9 children", value: 9 },
    { label: "10 children", value: 10 }
];


export const repeatedTimes = [
    { label: "06:00", value: "6" },
    { label: "07:00", value: "7" },
    { label: "08:00", value: "8" },
    { label: "09:00", value: "9" },
    { label: "10:00", value: "10" },
    { label: "11:00", value: "11" },
    { label: "12:00", value: "12" },
    { label: "13:00", value: "13" },
    { label: "14:00", value: "14" },
    { label: "15:00", value: "15" },
    { label: "16:00", value: "16" },
    { label: "17:00", value: "17" },
    { label: "18:00", value: "18" },
    { label: "19:00", value: "19" },
    { label: "20:00", value: "20" },

]


export const duration = [
    "1 hour",
    "2 hours",
    "3 hours",
    "4 hours",
    "5 hours",
    "6 hours",
    "7 hours",
    "8 hours",
    "9 hours",
    "10 hours",
    "11 hours",
    "12 hours",
    "13 hours",
    "14 hours",
    "15 hours",
    "16 hours",
    "17 hours",
    "18 hours",
    "19 hours",
    "20 hours",
    "21 hours",
    "22 hours",
    "23 hours",
    "24 hours",
    "25 hours",
    "26 hours",
    "27 hours",
    "28 hours",
    "29 hours",
    "30 hours",
    "31 hours",
    "32 hours",
    "33 hours",
    "34 hours",
    "35 hours",
    "36 hours",
    "37 hours",
    "38 hours",
    "39 hours",
    "40 hours",
    "41 hours",
    "42 hours",
    "43 hours",
    "44 hours",
    "45 hours",
    "46 hours",
    "47 hours",
    "+48 hours",
]

export const presetLocations = [
    { label: "Cairo", value: "Cairo" },
    { label: "Giza", value: "Giza" },
    { label: "Alexandria", value: "Alexandria" },
    { label: "Luxor", value: "Luxor" },
    { label: "Aswan", value: "Aswan" },
    { label: "Hurghada", value: "Hurghada" },
    { label: "Sharm El Sheikh", value: "Sharm El Sheikh" },
    { label: "Fayioum", value: "Fayioum" },
    { label: "Siwa", value: "Siwa" },
    { label: "Bahariya", value: "Bahariya" },
    { label: "Farafra", value: "Farafra" },
    { label: "Dakhla", value: "Dakhla" },
    { label: "Kharga", value: "Kharga" },
    { label: "Baris Oasis", value: "Baris Oasis" },
    { label: "Marsa Matrouh", value: "Marsa Matrouh" },
    { label: "El Alamein", value: "El Alamein" },
    { label: "Ras Sudr", value: "Ras Sudr" },
    { label: "Ras Shitan", value: "Ras Shitan" },
    { label: "Ras Abu Galum", value: "Ras Abu Galum" },
    { label: "Saint Catherine", value: "Saint Catherine" },
    { label: "Dahab", value: "Dahab" },
    { label: "Nuweiba", value: "Nuweiba" },
    { label: "Taba", value: "Taba" },
    { label: "Marsa Alam", value: "Marsa Alam" },
    { label: "El Gouna", value: "El Gouna" },
    { label: "Sahl Hasheesh", value: "Sahl Hasheesh" },
    { label: "Safaga", value: "Safaga" },
    { label: "Marsa Alam", value: "Marsa Alam" },
    { label: "Giza Pyramids", value: "Giza Pyramids" },
    { label: "Saqqara", value: "Saqqara" },
    { label: "Dahshur", value: "Dahshur" },
    { label: "Memphis", value: "Memphis" },
    { label: "Cairo Citadel", value: "Cairo Citadel" },
    { label: "Cairo Tower", value: "Cairo Tower" },
    { label: "Khan El Khalili", value: "Khan El Khalili" },
    { label: "Al Azhar Mosque", value: "Al Azhar Mosque" },
    { label: "Dahab", value: "Dahab" },
    { label: "Nuweiba", value: "Nuweiba" },
    { label: "Taba", value: "Taba" },
    { label: "Marsa Alam", value: "Marsa Alam" },
    { label: "El Gouna", value: "El Gouna" },
    { label: "Sahl Hasheesh", value: "Sahl Hasheesh" },
    { label: "Safaga", value: "Safaga" },
    { label: "Marsa Alam", value: "Marsa Alam" },
    { label: "Giza Pyramids", value: "Giza Pyramids" },
    { label: "Saqqara", value: "Saqqara" },
    { label: "Dahshur", value: "Dahshur" },
    { label: "Memphis", value: "Memphis" },
    { label: "Cairo Citadel", value: "Cairo Citadel" },
    { label: "Cairo Tower", value: "Cairo Tower" },
    { label: "Khan El Khalili", value: "Khan El Khalili" },
    { label: "Al Azhar Mosque", value: "Al Azhar Mosque" },
    { label: "Al Azhar Park", value: "Al Azhar Park" },
    { label: "Islamic Cairo", value: "Islamic Cairo" },
    { label: "Coptic Cairo", value: "Coptic Cairo" },
    { label: "Tahrir Square", value: "Tahrir Square" },
]


export const categoryOptions = [
    { label: "Cultural ", value: "Cultural Tours" },
    { label: "Historical ", value: "Historical Tours" },
    { label: "Adventure ", value: "Adventure Tours" },
    { label: "Religious ", value: "Religious Tours" },
    { label: "Safari ", value: "Safari Tours" },
    { label: "Desert ", value: "Desert Tours" },
    { label: "Beach ", value: "Beach Tours" },
    { label: "City ", value: "City Tours" },
    { label: "Shopping ", value: "Shopping Tours" },
    { label: "Family ", value: "Family Tours" },
    { label: "Honeymoon Tours", value: "Honeymoon Tours" },
    { label: "Luxury ", value: "Luxury Tours" },
    { label: "Budget ", value: "Budget Tours" },
    { label: "Group ", value: "Group Tours" },
    { label: "Private ", value: "Private Tours" },
    { label: "Custom Tours", value: "Custom Tours" },
    { label: "Educational ", value: "Educational Tours" },
    { label: "Photography ", value: "Photography Tours" },
    { label: "Food ", value: "Food Tours" },
    { label: "Wine ", value: "Wine Tours" },
    { label: "Beer ", value: "Beer Tours" },
    { label: "Spiritual ", value: "Spiritual Tours" },
    { label: "Health ", value: "Health Tours" },
    { label: "Yoga ", value: "Yoga Tours" },
    { label: "Meditation Tours", value: "Meditation Tours" },
    { label: "Pilgrimage Tours", value: "Pilgrimage Tours" },
    { label: "Cruise Tours", value: "Cruise Tours" },
    { label: "Fishing ", value: "Fishing Tours" },
    { label: "Golf ", value: "Golf Tours" },
    { label: "Hiking ", value: "Hiking Tours" },
    { label: "Cairo Day Tours", value: "Cairo Day Tours" },
    { label: "Luxor Day Tours", value: "Luxor Day Tours" },
    { label: "Aswan Day Tours", value: "Aswan Day Tours" },
    { label: "Hurghada Day Tours", value: "Hurghada Day Tours" },
    { label: "Sharm El Sheikh Day Tours", value: "Sharm El Sheikh Day Tours" },
    { label: "Fayoum Day Tours", value: "Fayoum Day Tours" },
    { label: "Siwa Day Tours", value: "Siwa Day Tours" },
    { label: "Bahariya Day Tours", value: "Bahariya Day Tours" },
    { label: "Farafra Day Tours", value: "Farafra Day Tours" },
    { label: "Dakhla Day Tours", value: "Dakhla Day Tours" },
    { label: "Kharga Day Tours", value: "Kharga Day Tours" },
    { label: "Baris Oasis Day Tours", value: "Baris Oasis Day Tours" },
    { label: "Marsa Matrouh Day Tours", value: "Marsa Matrouh Day Tours" },
    { label: "El Alamein Day Tours", value: "El Alamein Day Tours" },
    { label: "Ras Sudr Day Tours", value: "Ras Sudr Day Tours" },
    { label: "Ras Shitan Day Tours", value: "Ras Shitan Day Tours" },
    { label: "Ras Abu Galum Day Tours", value: "Ras Abu Galum Day Tours" },
    { label: "Saint Catherine Day Tours", value: "Saint Catherine Day Tours" },
    { label: "Dahab Day Tours", value: "Dahab Day Tours" },
    { label: "Nuweiba Day Tours", value: "Nuweiba Day Tours" },
    { label: "Taba Day Tours", value: "Taba Day Tours" },
    { label: "Marsa Alam Day Tours", value: "Marsa Alam Day Tours" },
    { label: "El Gouna Day Tours", value: "El Gouna Day Tours" },
    { label: "Sahl Hasheesh Day Tours", value: "Sahl Hasheesh Day Tours" },
    { label: "2 Day 1 Night Tours", value: "2 Day 1 Night Tours" },
    { label: "3 Day 2 Night Tours", value: "3 Day 2 Night Tours" },
    { label: "4 Day 3 Night Tours", value: "4 Day 3 Night Tours" },
    { label: "5 Day 4 Night Tours", value: "5 Day 4 Night Tours" },
    { label: "6 Day 5 Night Tours", value: "6 Day 5 Night Tours" },
    { label: "7 Day 6 Night Tours", value: "7 Day 6 Night Tours" },
    { label: "8 Day 7 Night Tours", value: "8 Day 7 Night Tours" },
    { label: "9 Day 8 Night Tours", value: "9 Day 8 Night Tours" },
    { label: "10 Day 9 Night Tours", value: "10 Day 9 Night Tours" },
    { label: "11 Day 10 Night Tours", value: "11 Day 10 Night Tours" },
    { label: "12 Day 11 Night Tours", value: "12 Day 11 Night Tours" },
    { label: "Top Rated Tours", value: "Top Rated Tours" },
    { label: "Nile Cruise Tours", value: "Nile Cruise Tours" },
    { label: "Shore Excursions", value: "Shore Excursions" },
    { label: "Cairo Airport Transfers", value: "Cairo Airport Transfers" },
    { label: "Luxor Airport Transfers", value: "Luxor Airport Transfers" },
    { label: "Aswan Airport Transfers", value: "Aswan Airport Transfers" },
    { label: "Hurghada Airport Transfers", value: "Hurghada Airport Transfers" },
    { label: "Sharm El Sheikh Airport Transfers", value: "Sharm El Sheikh Airport Transfers" },
]
